name: Root

packages:
  - "*"

scripts:
  ## App
  ## Can change [module] if need
  gen-app-icon:
    run: melos exec --fail-fast --scope="*app*" --flutter -- fvm flutter pub run flutter_launcher_icons
    description: Generates App resource app icon.

  gen-app-splash:
    run: melos exec --fail-fast --scope="*app*" --flutter -- fvm flutter pub run flutter_native_splash:create --flavors dev,prod
    description: Generates App resource splash screen.

  build-resources:
    run: melos exec --fail-fast --scope="*app*" --flutter -- fvm flutter packages pub run build_runner build --delete-conflicting-outputs
    description: Generates assets resource.

  gen-strings:
    run: melos exec --fail-fast --scope="*app*" --flutter -- fvm flutter pub run intl_utils:generate
    description: Generates strings resource.
  ## End App

  ## Data
  build-data:
    run: melos exec --fail-fast --scope="*data*" --flutter -- fvm flutter packages pub run build_runner build --delete-conflicting-outputs
    description: Generates data.

  ## End Data

  ## Domain
  build-domain:
    run: melos exec --fail-fast --scope="*domain*" --flutter -- fvm flutter packages pub run build_runner build --delete-conflicting-outputs
    description: Generates domain.

  ## End Domain

  ## Configs
  create-env:
    run: melos exec --fail-fast --scope="*configs*" "dart run lib/src/env.json.dart create"
    description: Create sample env file

  gen-env:
    run: melos exec --fail-fast --scope="*configs*" "dart run lib/src/env.json.dart $1"
    description: Generates env file
  ## End Configs
