name: resources
description: Resources module
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  intl_utils: ^2.8.3
  flutter_native_splash:
    git:
      url: https://github.com/lux-studio-66/flutter_native_splash.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons:
    git:
      url: https://github.com/lux-studio-66/flutter_launcher_icons.git
      ref: master
  melos: ^3.1.1

flutter_gen:
  output: lib/src/generated/assets

  # Optional
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true

  fonts:
    enabled: true

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
  output_dir: lib/src/generated/strings
  arb_dir: lib/src/strings

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/svgs/avatar/
    - assets/svgs/dialog/
    - assets/svgs/filled/tab/
    - assets/svgs/outline/tab/
    - assets/svgs/outline/appBar/
    - assets/svgs/outline/tagBadge/
    - assets/svgs/outline/progress/
    - assets/svgs/outline/textField/
    - assets/svgs/solid/progress/
    - assets/svgs/solid/textField/
    - assets/svgs/solid/datePicker/

    # To add assets to your package, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    #
    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # To add custom fonts to your package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
